### ISSUE TITLE
Changes to render-template broke existing installations.

### ISSUE THREAD

**Issue by dpagini** [lando/nginx#24]
I'm not entirely sure I understand what broke here, but upgrading Lando v3.14 => 3.18 broke for me, and I think I traced it back to PR  #19. It appears to me that my `appserver_nginx` container won't start, and my error is:

```
appserver_nginx_1  | Downloading render-template-1.0.5-5-linux-amd64-debian-10 package
appserver_nginx_1  | tar: render-template-1.0.5-5-linux-amd64-debian-10/files: Not found in archive
appserver_nginx_1  | tar: Exiting with failure status due to previous errors
```

Actually I guess what's happening is the container starts, hits this error, then then container kills itself and I don't have a webserver container.
I'm using the Pantheon recipe slightly tweaked for my company.
Happy to help troubleshoot what the issue is exactly, but I don't completely understand what's happening here, or how I can fix it for my team...?

**Comment by dpagini** [comment]
I think via the Pantheon plugin, I am using nginx 1.16...?

https://github.com/lando/pantheon/blob/ed3e800bf073e62270caebcd1908134eab6a7a19/recipes/pantheon/builder.js#L126

So maybe the check for the minor versions is not working... b/c w/ that version of nginx, I would expect to be using that "older" render-template (1.0.0-3), but based on my error message, it's trying to download that newer version...?

**Comment by reynoldsalec** [comment]
@dpagini closing this out based on updates in https://github.com/lando/lando/releases/tag/v3.20.6

Interesting historical note, but someone had this exact issue on a corporate environment back in 2021! https://github.com/lando/lando/issues/2987
